[default]
    default.locale = "tr-TR"

    [default.extend-words]
        Froms      = "Froms"      # Apple property key "kMDItemWhereFroms"
        Pn         = "Pn"         # flag used in script "-Pn"
        layou      = "layou"
        yucelbaba = "yuceltoluyag"
        nd         = "nd"

[files]
    extend-exclude = ["*.json", "*_cache", ".venv", "cache"]