# global settings
title: Linux & Ortaya Karışık
email: ytoluyag@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Bilgi 5 harflidir. 5 te 4'ü  İlgidir ;D
baseurl: ''
url: 'https://yuceltoluyag.github.io/'
permalink: '/:title/'
safe: false
port: 4000
lang: en
repository: https://github.com/yuceltoluyag/yuceltoluyag.github.io
timezone: Europe/Istanbul
lazyimages: true
default_img: /assets/images/svg/logo.svg
header:
  desktopMode: 'fixed'
  mobileMode: 'auto'

author:
  name: Yücel Toluyağ
  email: ytoluyag@gmail.com
  twitter: yuceltoluyag
twitter_username: yuceltoluyag
github_username: yuceltoluyag

# staticman (comments) configuration
staticman_url: https://minelyorum.herokuapp.com/v3/entry/github/yuceltoluyag/yuceltoluyag.github.io/master/comments

# google_site_verification: "ob8_FqKQlIxhp5eRJIvaR-bbkV_6kD7D9l_0TkzxMqc"
# Seo verification
verification:
  google: ob8_FqKQlIxhp5eRJIvaR-bbkV_6kD7D9l_0TkzxMqc
  yandex: 20bffb159da7d25c
  bing: 831DA09069414E7869C3F877F6417B6E

google_analytics:
  id: 'UA-156927338-1' # fill in your Google Analytics ID
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint: 'https://macro-polymer-336309.appspot.com/query?id=ahh6bG1-bWFjcm8tcG9seW1lci0zMzYzMDlyFQsSCEFwaVF1ZXJ5GICAgJjFqZMKDA'
    cache_path: false # the local PV cache data, friendly to visitors from GFW region

# Defaults
defaults:
  # _posts
  - scope:
      path: ''
      type: posts
    values:
      layout: post
  # _pages
  - scope:
      path: '_pages'
      type: pages # 参考 `site.collections`
    values:
      layout: page
      permalink: /:title/

collections:
  pages:
    output: true
    sort_by: order

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: chroma
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
keep_files: ['assets']
service-worker: true
pwa:
  sw_src_filepath: sw.js # Optional
  sw_dest_filename: sw.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 8 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - '/**/*.{js,json,css}'
    - '/**/*.{ico,jpg,jpeg,png,svg,webp}'
    - '/**/*.html'
  precache_glob_ignores: # Optional
    - 'sw.js'
    - 'assets/fonts/**/*'

include: ['_pages']
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-pwa-workbox
  - jekyll-sitemap
  - jekyll-archives
exclude:
  - gulpfile.babel.js
  - node_modules
  - package.json
  - package-lock.json
  - postcss.config.js
  - purgecss.config.js
  - README.md
  - src
  - bin
  - tailwind.config.js
  - netlify.toml
  - LICENSE
  - Gemfile
  - .babelrc
  - .gitignore
  - sass
  - scss
  - validate
  - gulp_tasks
  - api_data
  - ruby-version
  - .editorconfig
