---
name: Compress Images
on:
    workflow_dispatch:
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
        paths:
            - "**.jpg"
            - "**.jpeg"
            - "**.png"
            - "**.webp"

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    build:
        # Only run on Pull Requests within the same repository, and not from forks.
        if: github.event.pull_request.head.repo.full_name == github.repository
        name: calibreapp/image-actions
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Compress Images
              uses: calibreapp/image-actions@main
              with:
                  jpegQuality: "80"
                  jpegProgressive: false
                  pngQuality: "80"
                  webpQuality: "80"
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
